language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run backend sh -c "python manage.py test && flake8"
  - docker-compose run backend sh -c "python -m pytest GameEngine/tests/"
  - docker-compose run frontend  sh -c "yarn run eslint"