language: python
python:
  - "3.6"

services:
  - docker

before_script: 
  - pip install docker-compose

script:
  - docker-compose run --rm backend sh -c "pytest"
  - docker-compose run --rm frontend sh -c "yarn run test"
  - docker-compose run --rm backend sh -c "flake8"
  - docker-compose run --rm frontend sh -c "yarn run eslint"