version: "3.7"

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/Src:/Src
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=backend
      - DB_USER=postgres
      - DB_PASS=localpassword
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend/Src:/Frontend/Src
      - ./Frontend/.eslintrc:/Frontend/.eslintrc
      - ./Frontend/webpack.config.js:/Frontend/webpack.config.js
      - ./Frontend/index.html:/Frontend/index.html
      - ./Frontend/package.json:/Frontend/package.json
      - ./Frontend/.babelrc:/Frontend/.babelrc
    command: >
      sh -c "yarn run start"
    depends_on:
      - backend

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=localpassword