version: "3.7"

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./Backend/Src:/Src
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver ${HOST}:${BACKEND_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - FRONTEND_ORIGIN=${FRONTEND_HOST}:${FRONTEND_PORT}
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./Frontend/Src:/Frontend/Src
      - ./Frontend/.eslintrc:/Frontend/.eslintrc
      - ./Frontend/webpack.config.js:/Frontend/webpack.config.js
      - ./Frontend/index.html:/Frontend/index.html
      - ./Frontend/package.json:/Frontend/package.json
      - ./Frontend/.babelrc:/Frontend/.babelrc
    command: >
      sh -c "yarn run start"
    environment:
      - HOST=${HOST}
      - BASE_API_URL=${API_HOST}:${BACKEND_PORT}
      - BASE_WS_URL=${WS_HOST}:${BACKEND_PORT}
    depends_on:
      - backend

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}